blueprint:
  name: Badrum – Tänd & släck med valbara tider, veckodagar, nattläge och failsafe
  description: >
    Styr badrumsbelysningen med rörelsesensor, valbart veckoschema, nattläge och dynamisk failsafe-tid samt justerbar ljusnivågräns.
  domain: automation
  input:
    binary_sensor_motion:
      name: Rörelsesensor
      description: Sensor som registrerar rörelse
      selector:
        entity:
          domain: binary_sensor
    light_entity:
      name: Belysning
      description: Lampan som ska tändas/släckas
      selector:
        entity:
          domain: light
    lux_sensor:
      name: Ljusnivåsensor
      description: Sensor som mäter ljusnivå (lux)
      selector:
        entity:
          domain: sensor
    lux_threshold:
      name: Ljusnivå tröskel (lux)
      description: Maximalt lux-värde för att tända lampan (lampan tänds bara om lux är under detta värde)
      default: 95
      selector:
        number:
          min: 0
          max: 500
          unit_of_measurement: lx
          mode: slider
    input_text_last_scene:
      name: Input text - senaste scen
      description: En input_text som håller koll på senaste tända scenen
      selector:
        entity:
          domain: input_text
    scene_klart_ljus:
      name: Klart ljus scen
      description: Scen för dagtid med klart ljus
      selector:
        entity:
          domain: scene
    scene_nattlampa:
      name: Nattlampa scen
      description: Scen för nattläge
      selector:
        entity:
          domain: scene
    active_weekdays:
      name: Aktiva dagar
      description: Vilka dagar ska automationen vara aktiv?
      selector:
        select:
          multiple: true
          options:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
    active_start_time:
      name: Starttid
      description: Tid på dagen då belysningen ska aktiveras
      selector:
        time:
    active_end_time:
      name: Sluttid
      description: Tid på dagen då belysningen ska sluta aktiveras
      selector:
        time:
    failsafe_timer:
      name: Failsafe-timer (i minuter)
      description: Hur många minuter ska gå innan failsafen släcker ljuset?
      default: 15
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minuter
          mode: slider

trigger:
  - platform: state
    entity_id: !input binary_sensor_motion
    to: "on"
    id: motion_on
  - platform: state
    entity_id: !input binary_sensor_motion
    from: "on"
    to: "off"
    id: motion_off
  - platform: state
    entity_id: !input light_entity
    to: "on"
    id: light_on

mode: parallel
max: 100

action:
  - choose:
      - conditions:
          - condition: trigger
            id: motion_on
          - condition: numeric_state
            entity_id: !input lux_sensor
            below: !input lux_threshold
          - condition: time
            after: !input active_start_time
            before: !input active_end_time
            weekday: !input active_weekdays
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input scene_klart_ljus
          - service: input_text.set_value
            data:
              entity_id: !input input_text_last_scene
              value: klart_ljus

      - conditions:
          - condition: trigger
            id: motion_on
          - condition: not
            conditions:
              - condition: time
                after: !input active_start_time
                before: !input active_end_time
                weekday: !input active_weekdays
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input scene_nattlampa
          - service: input_text.set_value
            data:
              entity_id: !input input_text_last_scene
              value: nattlampa

      - conditions:
          - condition: trigger
            id: motion_off
          - condition: state
            entity_id: !input light_entity
            state: "on"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input input_text_last_scene
                    state: klart_ljus
                sequence:
                  - delay: "00:02:00"
                  - condition: state
                    entity_id: !input binary_sensor_motion
                    state: "off"
                  - service: light.turn_off
                    target:
                      entity_id: !input light_entity
              - conditions:
                  - condition: state
                    entity_id: !input input_text_last_scene
                    state: nattlampa
                sequence:
                  - delay: "00:01:00"
                  - condition: state
                    entity_id: !input binary_sensor_motion
                    state: "off"
                  - service: light.turn_off
                    target:
                      entity_id: !input light_entity

  # Dynamisk FAILSAFE – efter [failsafe_timer] minuter utan rörelse
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: motion_on
              - condition: trigger
                id: light_on
          - condition: state
            entity_id: !input light_entity
            state: "on"
        sequence:
          - wait_for_trigger:
              - platform: state
                entity_id: !input light_entity
                to: "off"
            timeout: "00:{{ '%02d' | format(!input.failsafe_timer | int) }}:00"
            continue_on_timeout: true

          - condition: state
            entity_id: !input light_entity
            state: "on"

          - condition: state
            entity_id: !input binary_sensor_motion
            state: "off"

          - service: light.turn_off
            target:
              entity_id: !input light_entity

          - service: logbook.log
            data:
              name: Badrum
              message: "Failsafe: Ljuset släcktes automatiskt efter {{ !input.failsafe_timer }} minuter utan rörelse."
