blueprint:
  name: Rörelsestyrd belysning (Scen eller Direkta lampor) med schema, nattläge och failsafe
  description: >
    Automatisera vilken belysning som helst med rörelsesensor, med separata dag- och nattinställningar,
    justerbar ljusnivågräns, valbara veckodagar och tider, samt failsafe-timer. Stöd för både scener och direkta lampor.
    Snapshot-återställning av tidigare ljusinställning ingår.
  domain: automation
  input:
    binary_sensor_motion:
      name: Rörelsesensor
      description: Sensor som registrerar rörelse
      selector:
        entity:
          domain: binary_sensor

    light_entity:
      name: Huvudlampa
      description: Den lampa som används för att kontrollera om belysningen är på (kan vara en lampa i gruppen)
      selector:
        entity:
          domain: light

    lux_sensor:
      name: Ljusnivåsensor
      description: Sensor som mäter omgivande ljusnivå (lux)
      selector:
        entity:
          domain: sensor

    lux_threshold:
      name: Ljusnivåtröskel
      description: Maximalt lux-värde för att tända lampan
      default: 95
      selector:
        number:
          min: 0
          max: 500
          unit_of_measurement: lx
          mode: slider

    input_text_last_scene:
      name: Input Text – Senaste scen
      description: Håller reda på senast aktiverad scen/läge
      selector:
        entity:
          domain: input_text

    # --- DAGINSTÄLLNINGAR ---
    scene_klart_ljus:
      name: Dag-scen (valfritt)
      description: Scen att aktivera under dagtid (lämna tom om direkta lampor används)
      default: []
      selector:
        entity:
          domain: scene

    day_lights:
      name: Daglampor (valfritt)
      description: Lampor att tända under dagtid (används om scen ej är satt)
      default: []
      selector:
        entity:
          domain: light
          multiple: true

    active_weekdays_day:
      name: Aktiva veckodagar (Dag)
      selector:
        select:
          multiple: true
          options: [mon, tue, wed, thu, fri, sat, sun]

    active_start_time_day:
      name: Starttid (Dag)
      selector:
        time:

    active_end_time_day:
      name: Sluttid (Dag)
      selector:
        time:

    # --- NATTINSTÄLLNINGAR ---
    scene_nattlampa:
      name: Natt-scen (valfritt)
      description: Scen att aktivera under natt (lämna tom om direkta lampor används)
      default: []
      selector:
        entity:
          domain: scene

    night_lights:
      name: Nattlampor (valfritt)
      description: Lampor att tända under natt (används om scen ej är satt)
      default: []
      selector:
        entity:
          domain: light
          multiple: true

    active_weekdays_night:
      name: Aktiva veckodagar (Natt)
      selector:
        select:
          multiple: true
          options: [mon, tue, wed, thu, fri, sat, sun]

    active_start_time_night:
      name: Starttid (Natt)
      selector:
        time:

    active_end_time_night:
      name: Sluttid (Natt)
      selector:
        time:

    failsafe_timer:
      name: Failsafe-timer (minuter)
      description: Hur många minuter innan ljuset släcks automatiskt utan rörelse
      default: 15
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minuter
          mode: slider

trigger:
  - platform: state
    entity_id: !input binary_sensor_motion
    to: "on"
    id: motion_on
  - platform: state
    entity_id: !input binary_sensor_motion
    from: "on"
    to: "off"
    id: motion_off
  - platform: state
    entity_id: !input light_entity
    to: "on"
    id: light_on

mode: parallel
max: 100

action:
  - choose:
      # --- DAGLÄGE ---
      - conditions:
          - condition: trigger
            id: motion_on
          - condition: numeric_state
            entity_id: !input lux_sensor
            below: !input lux_threshold
          - condition: time
            after: !input active_start_time_day
            before: !input active_end_time_day
            weekday: !input active_weekdays_day
        sequence:
          - service: scene.create
            data:
              scene_id: bathroom_before
              snapshot_entities: !input light_entity
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ (day_lights | length) > 0 }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input day_lights
              - default:
                  - service: scene.turn_on
                    target:
                      entity_id: !input scene_klart_ljus
          - service: input_text.set_value
            data:
              entity_id: !input input_text_last_scene
              value: klart_ljus

      # --- NATT ---
      - conditions:
          - condition: trigger
            id: motion_on
          - condition: time
            after: !input active_start_time_night
            before: !input active_end_time_night
            weekday: !input active_weekdays_night
        sequence:
          - service: scene.create
            data:
              scene_id: bathroom_before
              snapshot_entities: !input light_entity
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ (night_lights | length) > 0 }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input night_lights
              - default:
                  - service: scene.turn_on
                    target:
                      entity_id: !input scene_nattlampa
          - service: input_text.set_value
            data:
              entity_id: !input input_text_last_scene
              value: nattlampa

      # --- SLÄCKNING ---
      - conditions:
          - condition: trigger
            id: motion_off
          - condition: state
            entity_id: !input light_entity
            state: "on"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input input_text_last_scene
                    state: klart_ljus
                sequence:
                  - delay: "00:02:00"
                  - condition: state
                    entity_id: !input binary_sensor_motion
                    state: "off"
                  - service: scene.turn_on
                    target:
                      entity_id: scene.bathroom_before
              - conditions:
                  - condition: state
                    entity_id: !input input_text_last_scene
                    state: nattlampa
                sequence:
                  - delay: "00:01:00"
                  - condition: state
                    entity_id: !input binary_sensor_motion
                    state: "off"
                  - service: scene.turn_on
                    target:
                      entity_id: scene.bathroom_before

  # --- FAILSAFE ---
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: motion_on
              - condition: trigger
                id: light_on
          - condition: state
            entity_id: !input light_entity
            state: "on"
        sequence:
          - delay:
              minutes: !input failsafe_timer
          - condition: state
            entity_id: !input light_entity
            state: "on"
          - condition: state
            entity_id: !input binary_sensor_motion
            state: "off"
          - service: light.turn_off
            target:
              entity_id: !input light_entity
          - service: logbook.log
            data:
              name: Badrum
              message: "Failsafe: Ljuset släcktes automatiskt efter timeout."
