blueprint:
  name: Badrum – Tänd & släck med veckoschema, nattläge och failsafe
  description: >
    Styr badrumsbelysningen med rörelsesensor, veckoschema, nattläge och failsafe.
  domain: automation
  input:
    binary_sensor_motion:
      name: Rörelsesensor
      description: Sensor som registrerar rörelse
      selector:
        entity:
          domain: binary_sensor
    light_entity:
      name: Belysning
      description: Lampan som ska tändas/släckas
      selector:
        entity:
          domain: light
    lux_sensor:
      name: Ljusnivåsensor
      description: Sensor som mäter ljusnivå (lux)
      selector:
        entity:
          domain: sensor
    input_text_last_scene:
      name: Input text - senaste scen
      description: En input_text som håller koll på senaste tända scenen
      selector:
        entity:
          domain: input_text
    scene_klart_ljus:
      name: Klart ljus scen
      description: Scen för dagtid med klart ljus
      selector:
        entity:
          domain: scene
    scene_nattlampa:
      name: Nattlampa scen
      description: Scen för nattläge
      selector:
        entity:
          domain: scene

trigger:
  - platform: state
    entity_id: !input binary_sensor_motion
    to: "on"
    id: motion_on
  - platform: state
    entity_id: !input binary_sensor_motion
    from: "on"
    to: "off"
    id: motion_off

mode: parallel

action:
  - choose:
      - conditions:
          - condition: trigger
            id: motion_on
          - condition: numeric_state
            entity_id: !input lux_sensor
            below: 95
          - condition: state
            entity_id: !input binary_sensor_motion
            state: "on"
        sequence:
          # Här läggs hela logiken för veckodagar och nattläge in som vanligt
          # Denna del är inte förändrad av den nya failsafen

      - conditions:
          - condition: trigger
            id: motion_off
          - condition: state
            entity_id: !input light_entity
            state: "on"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input input_text_last_scene
                    state: klart_ljus
                sequence:
                  - delay: "00:02:00"
                  - condition: state
                    entity_id: !input binary_sensor_motion
                    state: "off"
                  - service: light.turn_off
                    target:
                      entity_id: !input light_entity
              - conditions:
                  - condition: state
                    entity_id: !input input_text_last_scene
                    state: nattlampa
                sequence:
                  - delay: "00:01:00"
                  - condition: state
                    entity_id: !input binary_sensor_motion
                    state: "off"
                  - service: light.turn_off
                    target:
                      entity_id: !input light_entity

  # Global failsafe – oavsett vad som tänt lampan
  - wait_for_trigger:
      - platform: state
        entity_id: !input light_entity
        to: "off"
    timeout: "00:15:00"
    continue_on_timeout: true

  - condition: state
    entity_id: !input light_entity
    state: "on"

  - service: light.turn_off
    target:
      entity_id: !input light_entity

  - service: logbook.log
    data:
      name: Badrum
      message: "Failsafe (global): Ljuset släcktes efter 15 minuter."