  homeassistant:
    name: badrum-tand-slack-blueprint
    version: 2025.07.27
    country: SE
    country_code: SE
    country_name: Sverige
    country_flag: 🇸🇪
    country_code_iso2: SE
    country_code_iso3: SWE
    country_code_num: 752
    country_code_alpha2: SE
    country_code_alpha3: SWE
    country_code_alpha_numeric: 752
    country_code_numeric: 752
    country_code_alpha2_numeric: SE
    country_code_alpha3_numeric: SWE
    country_code_alpha_numeric_numeric: 752
    country_code_numeric_numeric: 752
    country_code_alpha2_numeric_numeric: SE
    country_code_alpha3_numeric_numeric: SWE
    country_code_alpha_numeric_numeric_numeric: 752
    country_code_numeric_numeric_numeric: 752
    country_code_alpha2_numeric_numeric_numeric: SE
    country_code_alpha3_numeric_numeric_numeric: SWE
    country_code_alpha_numeric_numeric_numeric_numeric: 752
    country_code_numeric_numeric_numeric_numeric: 752
    country_code_alpha2_numeric_numeric_numeric_numeric: SE
    country_code_alpha3_numeric_numeric_numeric_numeric: SWE
    country_code_alpha_numeric_numeric_numeric_numeric_numeric: 752
    country_code_numeric_numeric_numeric_numeric_numeric: 752
    country_code_alpha2_numeric_numeric_numeric_numeric_numeric: SE
    country_code_alpha3_numeric_numeric_numeric_numeric_numeric: SWE
