blueprint:
  name: Rörelsestyrd belysning 4.2 – Stabil release med korrekt failsafe
  description: >
    Rörelsestyrd belysning med dag/natt, scener, lux, soluppgång/solnedgång,
    arbetsdag, failsafe, fasta avstängningstider (med veckodagar), snapshots och loggning.
    Auto-off-tider körs bara om ingen fast avstängningstid är aktiv.
  domain: automation
  input:
    
    # --- Sensorer & brytare ---
    
    motion_sensors:
      name: Rörelsesensor(er)
      default: []
      selector:
        entity:
          domain: binary_sensor
          multiple: true
          
    optional_switches:
      name: Valfri manuell brytare
      default: []
      selector:
        entity:
          domain: switch
          multiple: true

    # --- Lampor & scener ---
    
    main_lights:
      name: Huvudlampor
      default: []
      selector:
        target:
          entity:
            domain: light
            
    scene_day:
      name: Dagscen
      default: []
      selector:
        entity:
          domain: scene
          multiple: false
          
    scene_night:
      name: Nattscen
      default: []
      selector:
        entity:
          domain: scene
          multiple: false
          
    day_lights:
      name: Dagslampor
      default: []
      selector:
        target:
          entity:
            domain: light
            
    night_lights:
      name: Nattlampor
      default: []
      selector:
        target:
          entity:
            domain: light

    # --- Lux & sol ---
    
    lux_sensor:
      name: Luxsensor
      default: []
      selector:
        entity:
          domain: sensor
          device_class: illuminance
          
    lux_threshold:
      name: Luxgräns
      default: 50
      selector:
        number:
          min: 0
          max: 1000
          step: 1
          unit_of_measurement: lx
          
    use_sun_times:
      name: Använd soluppgång/solnedgång
      default: false
      selector:
        boolean: {}
        
    sunset_offset:
      name: Offset för solnedgång
      default: "-02:00:00"
      selector:
        text: {}
        
    sunrise_offset:
      name: Offset för soluppgång
      default: "+02:00:00"
      selector:
        text: {}
        
    sun_trigger_text:
      name: Input Text för sol-trigger
      default: []
      selector:
        entity:
          domain: input_text

    # --- Fasta avstängningstider ---
    
    fixed_off_time_1:
      name: Fast avstängningstid 1 (valfri)
      default: []
      selector:
        time: {}
        
    fixed_off_weekdays_1:
      name: Aktiva veckodagar (Fast tid 1)
      default: []
      selector:
        select:
          multiple: true
          options:
            - label: Måndag
              value: mon
            - label: Tisdag
              value: tue
            - label: Onsdag
              value: wed
            - label: Torsdag
              value: thu
            - label: Fredag
              value: fri
            - label: Lördag
              value: sat
            - label: Söndag
              value: sun
              
    fixed_off_time_2:
      name: Fast avstängningstid 2 (valfri)
      default: []
      selector:
        time: {}
        
    fixed_off_weekdays_2:
      name: Aktiva veckodagar (Fast tid 2)
      default: []
      selector:
        select:
          multiple: true
          options:
            - label: Måndag
              value: mon
            - label: Tisdag
              value: tue
            - label: Onsdag
              value: wed
            - label: Torsdag
              value: thu
            - label: Fredag
              value: fri
            - label: Lördag
              value: sat
            - label: Söndag
              value: sun

    # --- Tidinställningar ---
    
    day_start:
      name: Dagsstart
      default: "07:00:00"
      selector:
        time: {}
        
    day_end:
      name: Dagslut
      default: "22:00:00"
      selector:
        time: {}
        
    night_start:
      name: Nattstart
      default: "22:00:01"
      selector:
        time: {}
        
    night_end:
      name: Nattslut
      default: "07:00:00"
      selector:
        time: {}

    # --- Aktiva veckodagar ---
    
    active_weekdays_day:
      name: Aktiva veckodagar (Dag)
      default: []
      selector:
        select:
          multiple: true
          options:
            - label: Måndag
              value: mon
            - label: Tisdag
              value: tue
            - label: Onsdag
              value: wed
            - label: Torsdag
              value: thu
            - label: Fredag
              value: fri
            - label: Lördag
              value: sat
            - label: Söndag
              value: sun
              
    active_weekdays_night:
      name: Aktiva veckodagar (Natt)
      default: []
      selector:
        select:
          multiple: true
          options:
            - label: Måndag
              value: mon
            - label: Tisdag
              value: tue
            - label: Onsdag
              value: wed
            - label: Torsdag
              value: thu
            - label: Fredag
              value: fri
            - label: Lördag
              value: sat
            - label: Söndag
              value: sun

    # --- Arbetsdag & failsafe ---
    
    workday_sensor:
      name: Arbetsdagsensor
      default: []
      selector:
        entity:
          domain: binary_sensor
          
    enable_failsafe:
      name: Aktivera failsafe
      default: true
      selector:
        boolean: {}
        
    failsafe_timer_day:
      name: Failsafe-timer dag (minuter)
      default: 15
      selector:
        number:
          min: 1
          max: 120
          step: 1
          unit_of_measurement: min
          
    failsafe_timer_night:
      name: Failsafe-timer natt (minuter)
      default: 15
      selector:
        number:
          min: 1
          max: 120
          step: 1
          unit_of_measurement: min
          
    input_text_last_scene:
      name: Input Text - Senaste scen
      default: []
      selector:
        entity:
          domain: input_text

    # --- Auto-off-tider ---
    
    auto_off_main:
      name: Huvudlampors varaktighet (minuter)
      default: 10
      selector:
        number:
          min: 1
          max: 120
          step: 1
          unit_of_measurement: min
          mode: box
          
    auto_off_day:
      name: Dagslampors varaktighet (minuter)
      default: 5
      selector:
        number:
          min: 1
          max: 120
          step: 1
          unit_of_measurement: min
          mode: box
          
    auto_off_night:
      name: Nattlampors varaktighet (minuter)
      default: 1
      selector:
        number:
          min: 1
          max: 120
          step: 1
          unit_of_measurement: min
          mode: box

trigger:
  # --- Rörelsetriggers ---
  - platform: state
    entity_id: !input motion_sensors
    to: "on"
    id: motion_on
  - platform: state
    entity_id: !input motion_sensors
    to: "off"
    id: motion_off

  # --- Valfri brytare ---
  
  - platform: state
    entity_id: !input optional_switches
    to: "on"
    id: switch_on
  - platform: state
    entity_id: !input optional_switches
    to: "off"
    id: switch_off

  # --- Soltriggers ---
  
  - platform: sun
    event: sunrise
    offset: !input sunrise_offset
    id: sun_rise
  - platform: sun
    event: sunset
    offset: !input sunset_offset
    id: sun_set

  # --- Fasta avstängningstider ---
  
  - platform: time
    at: !input fixed_off_time_1
    id: fixed_off_1
  - platform: time
    at: !input fixed_off_time_2
    id: fixed_off_2

mode: restart  # viktigt för failsafe, förhindrar staplade timers

variables:
  main_lights_var: !input main_lights
  day_lights_var: !input day_lights
  night_lights_var: !input night_lights
  scene_day_var: !input scene_day
  scene_night_var: !input scene_night
  last_scene_entity: !input input_text_last_scene
  lux_sensor_var: !input lux_sensor
  lux_threshold_var: !input lux_threshold
  use_sun_times_var: !input use_sun_times
  workday_sensor_var: !input workday_sensor
  auto_off_main_var: !input auto_off_main
  auto_off_day_var: !input auto_off_day
  auto_off_night_var: !input auto_off_night
  fixed_off_weekdays_1_var: !input fixed_off_weekdays_1
  fixed_off_weekdays_2_var: !input fixed_off_weekdays_2
  fixed_off_time_1_var: !input fixed_off_time_1
  fixed_off_time_2_var: !input fixed_off_time_2
  day_start_var: !input day_start
  day_end_var: !input day_end
  night_start_var: !input night_start
  night_end_var: !input night_end
  active_weekdays_day_var: !input active_weekdays_day
  active_weekdays_night_var: !input active_weekdays_night
  enable_failsafe_var: !input enable_failsafe

condition: []

action:
  # --- Rörelse eller brytare PÅ ---
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: motion_on
              - condition: trigger
                id: switch_on
          - condition: template
            value_template: >
              {% set ls = lux_sensor_var %}
              {% if ls == [] %} true
              {% else %} 
                {% set val = states(ls[0]) %}
                {% if val in ['unknown', 'unavailable'] %} false
                {% else %} {{ val | float(9999) < lux_threshold_var }} {% endif %}
              {% endif %}
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ not use_sun_times_var }}"
                  - condition: time
                    after: !input day_start
                    before: !input day_end
                    weekday: !input active_weekdays_day
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ use_sun_times_var }}"
                  - condition: sun
                    after: sunrise
          - condition: template
            value_template: >
              {% set w = workday_sensor_var %}
              {% if w == [] %} true {% else %} {{ is_state(w[0], 'on') }} {% endif %}
        sequence:

          # Snapshot om huvudlampor finns
          
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ main_lights_var != [] }}"
                sequence:
                  - service: scene.create
                    data:
                      scene_id: snapshot_before_on
                      snapshot_entities: "{{ main_lights_var }}"

          # Prioritet: scene_day -> day_lights -> main_lights
          
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ scene_day_var != [] }}"
                sequence:
                  - service: scene.turn_on
                    target:
                      entity_id: "{{ scene_day_var }}"
              - conditions:
                  - condition: template
                    value_template: "{{ day_lights_var != [] }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ day_lights_var }}"
              - conditions:
                  - condition: template
                    value_template: "{{ main_lights_var != [] }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: "{{ main_lights_var }}"

          # Spara senaste scen
          
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ last_scene_entity != [] }}"
                sequence:
                  - service: input_text.set_value
                    data:
                      entity_id: "{{ last_scene_entity }}"
                      value: "dag/natt PÅ"
          - service: logbook.log
            data:
              name: Rörelsestyrning
              message: "Dag/natt PÅ aktiverad via rörelse eller brytare."

  # --- Rörelse eller brytare AV med auto-off, men ignorera om fast tid ---
  
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: motion_off
              - condition: trigger
                id: switch_off
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {% set now_ts = now().timestamp() %}
                      {% set fo1 = fixed_off_time_1_var %}
                      {% set fo2 = fixed_off_time_2_var %}
                      {% set fo1_ts = (fo1[0] if fo1 != [] else None) %}
                      {% set fo2_ts = (fo2[0] if fo2 != [] else None) %}
                      {% set fo_active = 
                        (fo1_ts is not none and now_ts < as_timestamp(fo1_ts)) or
                        (fo2_ts is not none and now_ts < as_timestamp(fo2_ts))
                      %}
                      {{ fo_active }}
                sequence: [] # Om fast tid är aktiv, gör inget
              - default:
                  - service: timer.start
                    data:
                      entity_id: timer.auto_off_main
                      duration: "{{ auto_off_main_var }}m"
                  - service: timer.start
                    data:
                      entity_id: timer.auto_off_day
                      duration: "{{ auto_off_day_var }}m"
                  - service: timer.start
                    data:
                      entity_id: timer.auto_off_night
                      duration: "{{ auto_off_night_var }}m"
                  - service: logbook.log
                    data:
                      name: Rörelsestyrning
                      message: >
                        Auto-off timers startade: huvudlampor {{ auto_off_main_var }} min,
                        dagslampor {{ auto_off_day_var }} min,
                        nattlampor {{ auto_off_night_var }} min.

  # --- Fasta avstängningstider med veckodagar ---
  
  - choose:
      - conditions:
          - condition: trigger
            id: fixed_off_1
          - condition: template
            value_template: >
              {{ now().strftime('%a').lower() in fixed_off_weekdays_1_var }}
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ main_lights_var + day_lights_var + night_lights_var }}"
          - service: logbook.log
            data:
              name: Rörelsestyrning
              message: "Fast avstängningstid 1 utförd."
      - conditions:
          - condition: trigger
            id: fixed_off_2
          - condition: template
            value_template: >
              {{ now().strftime('%a').lower() in fixed_off_weekdays_2_var }}
        sequence:
          - service: light.turn_off
            target:
              entity_id: "{{ main_lights_var + day_lights_var + night_lights_var }}"
          - service: logbook.log
            data:
              name: Rörelsestyrning
              message: "Fast avstängningstid 2 utförd."

  # --- Failsafe ---
  
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ enable_failsafe_var }}"
        sequence:
          - delay:
              minutes: "{{ failsafe_timer_day }}"
          - service: light.turn_off
            target:
              entity_id: "{{ main_lights_var + day_lights_var + night_lights_var }}"
          - service: logbook.log
            data:
              name: Rörelsestyrning
              message: >
                Failsafe utförd; alla lampor av efter {{ failsafe_timer_day }} min.
