blueprint:
  name: Rörelsestyrd belysning (Scen eller Direkta lampor) med schema, nattläge, solstyrning och failsafe
  description: >
    Styr valfri belysning med en eller flera rörelsesensorer, separata tider och/eller soluppgång/solnedgång för dag- och nattläge,
    justerbar ljusnivågräns (lux), dynamisk failsafe-timer och möjlighet att använda scen eller direkta lampor.
    Inkluderar snapshot-återställning.
  domain: automation
  input:
    motion_sensors:
      name: Rörelsesensor(er)
      description: Välj en eller flera rörelsesensorer.
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
          multiple: true
    optional_switches:
      name: Valfri manuell strömbrytare
      description: Välj en eller flera brytare som också ska trigga ljuset.
      default: []
      selector:
        entity:
          domain: switch
          multiple: true
    light_entity:
      name: Lampor
      description: Lampor som ska styras (används om ingen scen är vald).
      selector:
        entity:
          domain: light
          multiple: true
    scene_day:
      name: Scen dagläge
      description: Scen att aktivera på dagtid (valfritt, lämna tomt om du använder lampor direkt).
      default: []
      selector:
        entity:
          domain: scene
          multiple: false
    scene_night:
      name: Scen nattläge
      description: Scen att aktivera på nattetid (valfritt, lämna tomt om du använder lampor direkt).
      default: []
      selector:
        entity:
          domain: scene
          multiple: false
    lux_sensor:
      name: Lux-sensor (valfri)
      description: Lämna tom om du inte vill använda lux-gräns.
      default: []
      selector:
        entity:
          domain: sensor
          device_class: illuminance
          multiple: false
    lux_threshold:
      name: Lux-tröskel
      description: Slå bara på ljuset om lux är under detta värde.
      default: 50
      selector:
        number:
          min: 0
          max: 1000
          step: 1
          unit_of_measurement: lx
    use_sun_times:
      name: Använd soluppgång/solnedgång
      description: Aktivera för att styra dag/natt utifrån soluppgång och solnedgång.
      default: false
      selector:
        boolean: {}
    day_start:
      name: Dagstart (tid)
      default: "07:00:00"
      selector:
        time: {}
    day_end:
      name: Dagsslut (tid)
      default: "22:00:00"
      selector:
        time: {}
    failsafe_timer:
      name: Failsafe-timer (minuter)
      default: 30
      selector:
        number:
          min: 1
          max: 120
          step: 1
          unit_of_measurement: min

trigger:
  - platform: state
    entity_id: !input motion_sensors
    to: "on"
    id: motion_on
  - platform: state
    entity_id: !input optional_switches
    to: "on"
    id: switch_on
  - platform: state
    entity_id: !input light_entity
    to: "on"
    id: light_on

variables:
  use_sun_times: !input use_sun_times
  lux_sensor: !input lux_sensor
  lux_threshold: !input lux_threshold
  scene_day: !input scene_day
  scene_night: !input scene_night

condition: []

action:
  - choose:
      # --- DAGLÄGE ---
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: time
                    after: !input day_start
                    before: !input day_end
                  - condition: template
                    value_template: "{{ not use_sun_times }}"
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ use_sun_times }}"
                  - condition: or
                    conditions:
                      - condition: sun
                        after: sunrise
                        after_offset: "0:00:00"
                      - condition: sun
                        before: sunset
                        before_offset: "0:00:00"
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ lux_sensor == [] }}"
              - condition: numeric_state
                entity_id: !input lux_sensor
                below: !input lux_threshold
        sequence:
          - choose:
              - conditions: "{{ scene_day != [] }}"
                sequence:
                  - service: scene.create
                    data:
                      scene_id: before_day_scene
                      snapshot_entities: !input light_entity
                  - service: scene.turn_on
                    target:
                      entity_id: !input scene_day
              - conditions: "{{ scene_day == [] }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input light_entity

      # --- NATTLÄGE ---
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: time
                    after: !input day_end
                    before: !input day_start
                  - condition: template
                    value_template: "{{ not use_sun_times }}"
              - condition: and
                conditions:
                  - condition: template
                    value_template: "{{ use_sun_times }}"
                  - condition: or
                    conditions:
                      - condition: sun
                        after: sunset
                        after_offset: "0:00:00"
                      - condition: sun
                        before: sunrise
                        before_offset: "0:00:00"
          - condition: or
            conditions:
              - condition: template
                value_template: "{{ lux_sensor == [] }}"
              - condition: numeric_state
                entity_id: !input lux_sensor
                below: !input lux_threshold
        sequence:
          - choose:
              - conditions: "{{ scene_night != [] }}"
                sequence:
                  - service: scene.create
                    data:
                      scene_id: before_night_scene
                      snapshot_entities: !input light_entity
                  - service: scene.turn_on
                    target:
                      entity_id: !input scene_night
              - conditions: "{{ scene_night == [] }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input light_entity

  # --- FAILSAFE ---
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: motion_on
              - condition: trigger
                id: light_on
          - condition: state
            entity_id: !input light_entity
            state: "on"
        sequence:
          - delay:
              minutes: !input failsafe_timer
          - condition: state
            entity_id: !input light_entity
            state: "on"
          - condition: state
            entity_id: !input motion_sensors
            state: "off"
          - service: light.turn_off
            target:
              entity_id: !input light_entity
          - service: logbook.log
            data:
              name: Rörelsestyrning
              message: "Failsafe: Ljuset släcktes automatiskt efter timeout."

mode: parallel
max: 100