blueprint:
  name: Badrum – Tänd & släck med valbara tider, veckodagar, nattläge och failsafe
  description: >
    Styr badrumsbelysningen med rörelsesensor, individuella tider och veckodagar för klart ljus och nattläge,
    samt dynamisk failsafe-tid och justerbar ljusnivågräns.
  domain: automation
  input:
    binary_sensor_motion:
      name: Rörelsesensor
      description: Sensor som registrerar rörelse
      selector:
        entity:
          domain: binary_sensor
    light_entity:
      name: Belysning
      description: Lampan som ska tändas/släckas
      selector:
        entity:
          domain: light
    lux_sensor:
      name: Ljusnivåsensor
      description: Sensor som mäter ljusnivå (lux)
      selector:
        entity:
          domain: sensor
    lux_threshold:
      name: Ljusnivå tröskel (lux)
      description: Maximalt lux-värde för att tända lampan (lampan tänds bara om lux är under detta värde)
      default: 95
      selector:
        number:
          min: 0
          max: 500
          unit_of_measurement: lx
          mode: slider
    input_text_last_scene:
      name: Input text - senaste scen
      description: En input_text som håller koll på senaste tända scenen
      selector:
        entity:
          domain: input_text
    scene_klart_ljus:
      name: Klart ljus scen
      description: Scen för dagtid med klart ljus
      selector:
        entity:
          domain: scene
    scene_nattlampa:
      name: Nattlampa scen
      description: Scen för nattläge
      selector:
        entity:
          domain: scene
    daytime_weekdays:
      name: Veckodagar – Klart ljus
      description: Vilka dagar ska klart ljus-scen vara aktiv?
      selector:
        select:
          multiple: true
          options:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
    nighttime_weekdays:
      name: Veckodagar – Nattläge
      description: Vilka dagar ska nattlampa-scen vara aktiv?
      selector:
        select:
          multiple: true
          options:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
    daytime_start_time:
      name: Starttid – Klart ljus
      description: Tid på dagen då klart ljus-scen aktiveras
      selector:
        time:
    daytime_end_time:
      name: Sluttid – Klart ljus
      description: Tid på dagen då klart ljus-scen slutar vara aktiv
      selector:
        time:
    nighttime_start_time:
      name: Starttid – Nattläge
      description: Tid på dagen då nattlampa-scen aktiveras
      selector:
        time:
    nighttime_end_time:
      name: Sluttid – Nattläge
      description: Tid på dagen då nattlampa-scen slutar vara aktiv
      selector:
        time:
    failsafe_timer:
      name: Failsafe-timer (i minuter)
      description: Hur många minuter ska gå innan failsafen släcker ljuset?
      default: 15
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minuter
          mode: slider

trigger:
  - platform: state
    entity_id: !input binary_sensor_motion
    to: "on"
    id: motion_on
  - platform: state
    entity_id: !input binary_sensor_motion
    from: "on"
    to: "off"
    id: motion_off
  - platform: state
    entity_id: !input light_entity
    to: "on"
    id: light_on

mode: parallel
max: 100

action:
  - choose:
      - conditions:
          - condition: trigger
            id: motion_on
          - condition: numeric_state
            entity_id: !input lux_sensor
            below: !input lux_threshold
          - condition: time
            after: !input daytime_start_time
            before: !input daytime_end_time
            weekday: !input daytime_weekdays
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input scene_klart_ljus
          - service: input_text.set_value
            data:
              entity_id: !input input_text_last_scene
              value: klart_ljus

      - conditions:
          - condition: trigger
            id: motion_on
          - condition: time
            after: !input nighttime_start_time
            before: !input nighttime_end_time
            weekday: !input nighttime_weekdays
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input scene_nattlampa
          - service: input_text.set_value
            data:
              entity_id: !input input_text_last_scene
              value: nattlampa

      - conditions:
          - condition: trigger
            id: motion_off
          - condition: state
            entity_id: !input light_entity
            state: "on"
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input input_text_last_scene
                    state: klart_ljus
                sequence:
                  - delay: "00:02:00"
                  - condition: state
                    entity_id: !input binary_sensor_motion
                    state: "off"
                  - service: light.turn_off
                    target:
                      entity_id: !input light_entity
              - conditions:
                  - condition: state
                    entity_id: !input input_text_last_scene
                    state: nattlampa
                sequence:
                  - delay: "00:01:00"
                  - condition: state
                    entity_id: !input binary_sensor_motion
                    state: "off"
                  - service: light.turn_off
                    target:
                      entity_id: !input light_entity

  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: trigger
                id: motion_on
              - condition: trigger
                id: light_on
          - condition: state
            entity_id: !input light_entity
            state: "on"
        sequence:
          - delay:
              minutes: !input failsafe_timer
          - condition: state
            entity_id: !input light_entity
            state: "on"
          - condition: state
            entity_id: !input binary_sensor_motion
            state: "off"
          - service: light.turn_off
            target:
              entity_id: !input light_entity
          - service: logbook.log
            data:
              name: Badrum
              message: "Failsafe: Ljuset släcktes automatiskt efter angiven tid utan rörelse."
